# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'CraftExchange' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CraftExchange
  pod 'JGProgressHUD'
  pod 'Bond'
  pod 'ReactiveKit'
  pod 'RealmSwift'
  pod 'Eureka'
  pod 'RichTextRow'
  pod 'SwiftKeychainWrapper'
  pod 'ReachabilitySwift'
  pod 'SideMenu'
end
